nodeLinker: node-modules

packageExtensions:
  "@11ty/eleventy-plugin-bundle@*":
    peerDependencies:
      posthtml: "*"
  resend@*:
    peerDependencies:
      react: "*"
      react-dom: "*"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
