name: Pre-build 11ty

on:
  pull_request:
    branches:
      - main

env:
  ELEVENTY_ENV: production

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Build site (dry run)
        run: yarn build:dryrun
      
      - name: Build site
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: 11ty-staging
